//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSum.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckSum.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum files created ({0} files).
        /// </summary>
        internal static string Checksum_files_created {
            get {
                return ResourceManager.GetString("Checksum_files_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum files verified ({0} files) : .
        /// </summary>
        internal static string Checksum_files_verified {
            get {
                return ResourceManager.GetString("Checksum_files_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        internal static string Checksum_files_verified_FAILED {
            get {
                return ResourceManager.GetString("Checksum_files_verified_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string Checksum_files_verified_SUCCESS {
            get {
                return ResourceManager.GetString("Checksum_files_verified_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hash: {0}.
        /// </summary>
        internal static string CreateCheckSum_Global_hash {
            get {
                return ResourceManager.GetString("CreateCheckSum_Global_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing checksum files !.
        /// </summary>
        internal static string Error_Missing_checksum_files {
            get {
                return ResourceManager.GetString("Error_Missing_checksum_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1} / {2} {4:0.0}% {3:0}s remaining {5}.
        /// </summary>
        internal static string GetProgressMessage_BoundedTask {
            get {
                return ResourceManager.GetString("GetProgressMessage_BoundedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1} / {2} completed in {3:0.0}s {4}.
        /// </summary>
        internal static string GetProgressMessage_CompletedTask {
            get {
                return ResourceManager.GetString("GetProgressMessage_CompletedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string GetProgressMessage_Item {
            get {
                return ResourceManager.GetString("GetProgressMessage_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string GetProgressMessage_Items {
            get {
                return ResourceManager.GetString("GetProgressMessage_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}{4} {2:0}s {3}.
        /// </summary>
        internal static string GetProgressMessage_UnboundedTask {
            get {
                return ResourceManager.GetString("GetProgressMessage_UnboundedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file ({0}).
        /// </summary>
        internal static string Win32File_Error_opening_file {
            get {
                return ResourceManager.GetString("Win32File_Error_opening_file", resourceCulture);
            }
        }
    }
}
